version: '2'
services:
  redis-7000:
    image: redis:4.0.9
    restart: always
    network_mode: "host"
    volumes:
      - ./redis-7000.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-7001:
    image: redis:4.0.9
    restart: always
    network_mode: "host"
    volumes:
      - ./redis-7001.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-7002:
    image: redis:4.0.9
    restart: always
    network_mode: "host"
    volumes:
      - ./redis-7002.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-7003:
    image: redis:4.0.9
    restart: always
    network_mode: "host"
    volumes:
      - ./redis-7003.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-7004:
    image: redis:4.0.9
    restart: always
    network_mode: "host"
    volumes:
      - ./redis-7004.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-7005:
    image: redis:4.0.9
    restart: always
    network_mode: "host"
    volumes:
      - ./redis-7005.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  ruby:
    image: ruby
    restart: always
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - ./:/tmp/data
    command: bash